export const API = {
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
    switchTenant: "/api/v1/auth/switch-tenant",
  },
  calls: {
    list: "/api/v1/calls",
    detail: (id: string) => `/api/v1/calls/${id}`,
    recording: (id: string) => `/api/v1/calls/${id}/recording`,
    outbound: "/api/v1/calls/outbound",
  },
  admin: {
    brand: "/api/v1/admin/brand",
    assistant: "/api/v1/admin/assistant",
    contacts: "/api/v1/admin/contacts",
    contactDetail: (id: string) => `/api/v1/admin/contacts/${id}`,
    workingHours: "/api/v1/admin/working-hours",
    team: "/api/v1/admin/team",
    teamInvite: "/api/v1/admin/team/invite",
    phoneNumbers: "/api/v1/admin/phone-numbers",
    billing: "/api/v1/admin/billing",
    usage: "/api/v1/admin/usage",
    upgradeRequest: "/api/v1/admin/billing/upgrade-request",
  },
  platform: {
    tenants: "/api/v1/platform/tenants",
    tenantDetail: (id: string) => `/api/v1/platform/tenants/${id}`,
    tenantBrand: (id: string) => `/api/v1/platform/tenants/${id}/brand`,
    tenantAssistant: (id: string) => `/api/v1/platform/tenants/${id}/assistant`,
    tenantSubscription: (id: string) => `/api/v1/platform/tenants/${id}/subscription`,
    tenantLanguages: (id: string) => `/api/v1/platform/tenants/${id}/languages`,
    tenantAdmins: (id: string) => `/api/v1/platform/tenants/${id}/admins`,
    tenantProviders: (id: string) =>
      `/api/v1/platform/tenants/${id}/providers`,
    providers: "/api/v1/platform/providers",
    plans: "/api/v1/platform/plans",
    planDetail: (id: string) => `/api/v1/platform/plans/${id}`,
  },
} as const;
